base:
  project: airtemp
  random_state: 42
  target_col: Air temperature [K]

data_source:
  s3_source: data_given/Final_data.csv

load_data:
  raw_dataset_csv: data/raw/Final_data.csv

split_data:
  train_path: data/processed/train_Final_data.csv
  test_path: data/processed/test_Final_data.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
       alpha: 0.00516461423854359
       l1_ratio: 0.5
#      alpha: 0.9
#      l1_ratio: 0.4
model_dir: saved_models

#reports:
#  params: report/params.json
#  scores: report/scores.json
#
#webapp_model_dir: prediction_service/model/model.joblib