base:
  project: airtemp
  random_state: 42
  target_col: Air_temperature_[K]

data_source:
  s3_source: data_given/Final_data.csv

load_data:
  raw_dataset_csv: data/raw/Final_data.csv

split_data:
  train_path: data/processed/train_Final_data.csv
  test_path: data/processed/test_Final_data.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
#       alpha: 0.01516461423854359
#       l1_ratio: 0.6
#      alpha: 0.02
#      l1_ratio: 0.7
#       alpha: 0.008
#       l1_ratio: 0.65
       alpha: 0.02516461423854359
       l1_ratio: 0.6


model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir : artifacts
  experiment_name : ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetAirTempModel
  remote_server_uri: http://localhost:1234